accounts/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="home"),
    path("logout/", lambda request: redirect("/admin/logout", permanent=False)),
]

city/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path(
        "",
        views.CityListView.as_view(),
        name="city_list",
    ),
    path(
        "search/",
        views.CitySearchView,
        name="city_search",
    ),
    path(
        "create/",
        views.CityCreateView.as_view(),
        name="city_create",
    ),
    path("<int:pk>/", views.CityDetailsView.as_view(), name="city_detail"),
    path(
        "<int:pk>/edit/",
        views.CityEditView.as_view(),
        name="city_update",
    ),
    path(
        "<int:pk>/delete/",
        views.CityDeleteView.as_view(),
        name="city_delete",
    ),
]

erp_luciano_martins_htmx/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
    path("city/", include("city.urls")),
    path("gasto/", include("gasto.urls")),
    path("events/", include("events.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from accounts import constants


class Base(models.Model):
    """Base parent model for all the models"""

    created_at = models.DateTimeField("Criado em", auto_now_add=True, null=True)
    modified_at = models.DateTimeField("Atualizado em", auto_now=True, null=True)
    status = models.BooleanField(choices=constants.STATUS, default=constants.ATIVO)

    class Meta:
        abstract = True


class User(AbstractUser):
    username = models.CharField(
        "Usuário",
        max_length=30,
        unique=True,
    )
    name = models.CharField("Nome", max_length=100, blank=True)
    first_name = models.CharField("Primeiro Nome", max_length=150, blank=True)
    last_name = models.CharField("Último Nome", max_length=150, blank=True)
    email = models.EmailField("E-mail", unique=True)
    is_staff = models.BooleanField("Equipe", default=False)
    is_active = models.BooleanField("Ativo", default=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.name or self.username

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"
        db_table = "accounts_user"

gasto/models.py
from django.db import models

from accounts import constants
from accounts.models import Base


class Segmento(Base):
    name = models.CharField("Tipo de comércio", max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Segmento"
        verbose_name_plural = "Segmentos"
        ordering = ["-name"]


class Cardbank(Base):
    name = models.CharField("Nome", max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Banco do cartão"
        verbose_name_plural = "Bancos do cartão"
        ordering = ["-id"]
        # db_table = 'website_cardbank'


def cardbank_default():
    return Cardbank.objects.get(id=1).id


class Gasto(Base):
    name = models.CharField("nome", max_length=100)
    more_infos = models.CharField(
        "Infos Complementares",
        max_length=100,
        null=True,
        blank=True,
    )
    datagasto = models.DateField("Data do Gasto")
    total = models.CharField("Valor Total", max_length=100, null=True, blank=True)
    description_on_invoice = models.CharField(
        "Descrição na fatura", max_length=20, null=True, blank=True
    )
    opcoes_cartao = models.CharField(
        "Tipo de pagamento",
        max_length=1,
        choices=constants.CARTAO,
        default=constants.CREDITO,
    )
    segmento = models.ForeignKey(
        Segmento, related_name="segmento", on_delete=models.PROTECT
    )
    card_bank = models.ForeignKey(
        Cardbank,
        verbose_name="Banco do cartão",
        related_name="cardbanks",
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return f"{self.id}-{self.name}"

    class Meta:
        verbose_name = "Gasto"
        verbose_name_plural = "Gastos"
        ordering = ["-datagasto"]

    @property
    def soma(self):
        resultado = 0
        try:
            resultado = sum(
                round(float(item.valor_parcela.replace(",", ".")), 2)
                for item in self.parcelas_gasto.all()
            )
        except ValueError as err:
            print(err)
        return resultado


class Parcelas(models.Model):
    gasto = models.ForeignKey(
        Gasto, related_name="parcelas_gasto", on_delete=models.CASCADE
    )
    parcelas = models.IntegerField("Total de parcelas", default=1)
    numero_parcela = models.IntegerField("Número da parcela", default=1)
    valor_parcela = models.CharField(
        "Valor da Parcela", max_length=100, blank=True, null=True
    )
    data_parcela = models.DateField("Data Parcela", blank=True, null=True)

    class Meta:
        verbose_name = "Parcela do gasto"
        verbose_name_plural = "Parcelas dos gasto"

    def __str__(self):
        return f"SEGMENTO..:{self.gasto.name} - PARCELA..:{self.parcelas}"

accounts/views.py
from django.shortcuts import render

from city.models import City


def index(request):
    template_name = "home.html"
    cities = City.objects.all()
    context = {"cities": [{"id": r.id, "nome": str(r)} for r in cities[:5]]}
    return render(request, template_name, context)

accounts/templates/includes/add_modal.html
<!-- addModal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel">
  <div class="modal-dialog" role="document">
    <div id="addContent" class="modal-content">
      <!-- O novo conteúdo será inserido aqui. -->
      <div class="modal-header">
        <h4 class="modal-title" id="detailModalLabel">Modal title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div>

accounts/templates/includes/nav.html
<!-- includes/nav.html -->
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'accounts:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'city_list' %}">Localidades</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gasto_list' %}">Gastos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{ url 'expense:expense_list' %}">Despesas</a>
      </li>
      <li class="nav-item" style="background-color: aqua">
        <div>
            <button class="btn btn-light" onclick="swapStyles('light.css')">Light Mode</button>
            <button class="btn btn-dark" onclick="swapStyles('dark.css')">Dark Mode</button>
        </div>
      </li>
    </ul>
  </div>
</nav>

accounts/templates/includes/navbar.html
<!-- includes/nav.html -->
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'accounts:home' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'city_list' %}">Localidades</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gasto_list' %}">Gastos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'read_pdf' %}">Ler PDF</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'read_itau_txt' %}">Acessar ITAÚ TXT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'access_itau' %}">Acessar ITAÚ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'event_list' %}">Acontecimentos</a>
      </li>
      <li class="nav-item" style="background-color: aqua">
        <div>
            <button class="btn btn-light" onclick="swapStyles('light.css')">Light Mode</button>
            <button class="btn btn-dark" onclick="swapStyles('dark.css')">Dark Mode</button>
        </div>
      </li>
    </ul>
  </div>
</nav>